Resources:
  TodosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${file(resource/index.json):todo.todosTable}
      AttributeDefinitions:
        - AttributeName: todo_id
          AttributeType: S
      KeySchema:
        - AttributeName: todo_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
